### ISSUE TITLE
[Bug] cudaFree() error when use meta-schedule 

### ISSUE THREAD

**Issue by KangHe000** [apache/tvm#13639]
### Expected behavior

Hi, I try to run the test_cuda_tensor_core() of test_auto_tensorize.py: https://github.com/apache/tvm/blob/main/tests/python/integration/test_auto_tensorize.py

but got cudaFree() error below. 

### Actual behavior

```
One or more operators have not been tuned. Please tune your model for better performance. Use DEBUG logging level to see more details.
terminate called after throwing an instance of 'tvm::runtime::InternalError'
  what():  [21:57:23] /home/hekang/gitlab_src/tvm/src/runtime/cuda/cuda_device_api.cc:135: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (e == cudaSuccess || e == cudaErrorCudartUnloading) is false: CUDA: unspecified launch failure
Stack trace:
  0: _ZN3tvm7runtime6detail
  1: tvm::runtime::CUDADeviceAPI::FreeDataSpace(DLDevice, void*)
  2: tvm::runtime::NDArray::Internal::DefaultDeleter(tvm::runtime::Object*)
  3: tvm::runtime::GraphExecutor::~GraphExecutor()
  4: _ZN3tvm7runtime18SimpleObjAllocator7
  5: tvm::runtime::GraphExecutorFactory::ExecutorCreate(std::vector<DLDevice, std::allocator<DLDevice> > const&)
  6: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::GraphExecutorFactory::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::$_0> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  7: TVMFuncCall


Aborted (core dumped)
```

### Environment

target = tvm.target.Target("nvidia/geforce-rtx-2080-ti")
ubuntu18.04 
cuda102 
torch1.12.1+cu102

### code to reproduce

```
"""Integration test for MetaSchedule's auto tensorization."""
import tempfile
import numpy as np
import pytest
import tvm
import tvm.testing
import tvm.topi.testing
from tvm import meta_schedule as ms
from tvm import relay
from tvm.meta_schedule.testing import relay_workload

def test_cuda_tensor_core(model_name, input_shape):
    """Integration tests of auto tensorization with CUDA tensor core"""
    target = tvm.target.Target("nvidia/geforce-rtx-2080-ti")
    dev = tvm.cuda()
    if model_name.startswith("bert"):
        data = tvm.nd.array(np.random.randint(0, 30521, size=input_shape), dev)  # embedding size
    else:
        data = tvm.nd.array(np.random.randn(*input_shape).astype("float32"), dev)

    mod, params, (input_name, _, _) = relay_workload.get_network(model_name, input_shape)
    seq = tvm.transform.Sequential(
        [
            relay.transform.ToMixedPrecision(),
        ]
    )
    with tvm.transform.PassContext(opt_level=3):
        mod = seq(mod)

    def convert_layout(mod):
        seq = tvm.transform.Sequential(
            [relay.transform.ConvertLayout({"nn.conv2d": ["NHWC", "OHWI"]})]
        )
        with tvm.transform.PassContext(opt_level=3):
            mod = seq(mod)
        return mod
    with tempfile.TemporaryDirectory() as work_dir:
        with ms.Profiler() as profiler:
            converted_mod = convert_layout(mod)
            database = ms.relay_integration.tune_relay(
                mod=converted_mod,
                target=target,
                work_dir=work_dir,
                max_trials_global=3000,
                params=params,
            )
            rt_mod1 = ms.relay_integration.compile_relay(
                database=database,
                mod=converted_mod,
                target=target,
                params=params,
            )
        print(profiler.table())

        # Compile without MetaSchedule for correctness check
        with tvm.transform.PassContext(opt_level=0):
            rt_mod2 = relay.build(mod, target=target, params=params)

        def get_output(data, lib):
            module = tvm.contrib.graph_executor.GraphModule(lib["default"](dev))
            module.set_input(input_name, data)
            module.run()
            return module.get_output(0).numpy()

        # Check correctness
        actual_output = get_output(data, rt_mod1)
        print("actual_output = ", actual_output)
        expected_output = get_output(data, rt_mod2)
        print("expected_output = ", expected_output)

        assert np.allclose(actual_output, expected_output, rtol=1e-2, atol=2e-2)

if __name__ == "__main__":
    model_name = "bert_base"
    input_shape = (8, 128)
    test_cuda_tensor_core(model_name, input_shape)
    

```

### Triage
* needs-triage

**Comment by masahi** [comment]
I can reproduce this. I ran this test before and it worked fine then. Looking.

**Comment by masahi** [comment]
@vinx13 @zxybazh Does this also reproduce in your environment? It fails for both resnet and bert for me. Quick tuning setting like
```
num_trials_per_iter=8,
max_trials_per_task=8,
strategy="replay-trace"
```
is fine to cause this failure. 

I also went to back to a commit where this test was working fine for me, but still got the same failure now for some reason. One difference with my previous setting is that now I'm on CUDA 12 while I was on 11.6 when this test ran successfully.

**Comment by vinx13** [comment]
I can run on coda 11.6 with latest main 6dbb7e without problems

**Comment by zxybazh** [comment]
Can reproduce same error, the stack trace is a bit different, run on latest main 6dbb7e1a5e357ee829348a1c1953b32837e68289 with cuda 11.8, target `nvidia/geforce-rtx-3070` and torch version `1.12.1+cu116`.
```
terminate called after throwing an instance of 'tvm::runtime::InternalError'
  what():  [11:11:03] /home/zxybazh/tvm-tensorir/src/runtime/cuda/cuda_device_api.cc:135: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (e == cudaSuccess || e == cudaErrorCudartUnloading) is false: CUDA: unspecified launch failure
Stack trace:
  0: tvm::runtime::CUDADeviceAPI::FreeDataSpace(DLDevice, void*)
        at /home/zxybazh/tvm-tensorir/src/runtime/cuda/cuda_device_api.cc:131
  1: tvm::runtime::NDArray::Internal::DefaultDeleter(tvm::runtime::Object*)
        at /home/zxybazh/tvm-tensorir/src/runtime/ndarray.cc:107
  2: tvm::runtime::Object::DecRef()
        at /home/zxybazh/tvm-tensorir/include/tvm/runtime/object.h:805
  3: tvm::runtime::Object::DecRef()
        at /home/zxybazh/tvm-tensorir/include/tvm/runtime/object.h:801
  4: tvm::runtime::ObjectPtr<tvm::runtime::Object>::reset()
        at /home/zxybazh/tvm-tensorir/include/tvm/runtime/object.h:451
  5: tvm::runtime::ObjectPtr<tvm::runtime::Object>::~ObjectPtr()
        at /home/zxybazh/tvm-tensorir/include/tvm/runtime/object.h:400
  6: tvm::runtime::ObjectRef::~ObjectRef()
        at /home/zxybazh/tvm-tensorir/include/tvm/runtime/object.h:511
  7: tvm::runtime::NDArray::~NDArray()
        at /home/zxybazh/tvm-tensorir/include/tvm/runtime/ndarray.h:59
  8: void std::_Destroy<tvm::runtime::NDArray>(tvm::runtime::NDArray*)
        at /usr/include/c++/11/bits/stl_construct.h:140
  9: void std::_Destroy_aux<false>::__destroy<tvm::runtime::NDArray*>(tvm::runtime::NDArray*, tvm::runtime::NDArray*)
        at /usr/include/c++/11/bits/stl_construct.h:152
  10: void std::_Destroy<tvm::runtime::NDArray*>(tvm::runtime::NDArray*, tvm::runtime::NDArray*)
        at /usr/include/c++/11/bits/stl_construct.h:185
  11: void std::_Destroy<tvm::runtime::NDArray*, tvm::runtime::NDArray>(tvm::runtime::NDArray*, tvm::runtime::NDArray*, std::allocator<tvm::runtime::NDArray>&)
        at /usr/include/c++/11/bits/alloc_traits.h:746
  12: std::vector<tvm::runtime::NDArray, std::allocator<tvm::runtime::NDArray> >::~vector()
        at /usr/include/c++/11/bits/stl_vector.h:680
  13: tvm::runtime::GraphExecutor::~GraphExecutor()
        at /home/zxybazh/tvm-tensorir/src/runtime/graph_executor/graph_executor.h:67
  14: tvm::runtime::SimpleObjAllocator::Handler<tvm::runtime::GraphExecutor>::Deleter_(tvm::runtime::Object*)
        at /home/zxybazh/tvm-tensorir/include/tvm/runtime/memory.h:138
  15: tvm::runtime::ObjectPtr<tvm::runtime::GraphExecutor>::reset()
        at /home/zxybazh/tvm-tensorir/include/tvm/runtime/object.h:451
  16: tvm::runtime::ObjectPtr<tvm::runtime::GraphExecutor>::~ObjectPtr()
        at /home/zxybazh/tvm-tensorir/include/tvm/runtime/object.h:400
  17: tvm::runtime::GraphExecutorFactory::ExecutorCreate(std::vector<DLDevice, std::allocator<DLDevice> > const&)
        at /home/zxybazh/tvm-tensorir/src/runtime/graph_executor/graph_executor_factory.cc:125
  18: operator()
        at /home/zxybazh/tvm-tensorir/src/runtime/graph_executor/graph_executor_factory.cc:55
  19: Call
        at /home/zxybazh/tvm-tensorir/include/tvm/runtime/packed_func.h:1213
  20: tvm::runtime::PackedFuncObj::CallPacked(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /home/zxybazh/tvm-tensorir/include/tvm/runtime/packed_func.h:1217
  21: TVMFuncCall
        at /home/zxybazh/tvm-tensorir/src/runtime/c_runtime_api.cc:477
```

**Comment by Hzfengsy** [comment]
Google says this error may be caused by freeing memory before the kernel ends, e.g., missing the `Synchronize` instruction. I'm not sure what happens actually and only provide some information.

**Comment by vinx13** [comment]
I also passed test on CUDA 12.0 (I updated target to rtx-3070 on my machine)

**Comment by junrushao** [comment]
Can we try:

```diff
- module.run()
- return module.get_output(0).numpy()
+ module.run()
+ result = module.get_output(0).numpy()
+ del module
+ return result
```

This prevents `module` from early destruction

**Comment by masahi** [comment]
It seems the error happens before or at the very start of `run` - I added a debug print to see at which kernel this error is raised, but nothing is logged before the error is emitted.

I have some finding on this issue. I'm pretty sure it is related to CUDA driver version, and in particular, it is related to how PyTorch (used to generate the input models) is installed. If I serialize the created module once, and run the test without importing PT ever, the test runs successfully. 

I also get this warning from PT during tracing, which supports my hypothesis. @KangHe000 @zxybazh Do you get this warning as well?
```
/home/masa/miniconda3/lib/python3.9/site-packages/torch/jit/_trace.py:443: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
```

**Comment by junrushao** [comment]
That could be very likely the cause, and that's why we usually carefully isolate PyTorch in a separate process to avoid such problems in MetaSchedule experiments.

**Comment by vinx13** [comment]
@masahi i actually got the same warning but it runs well. I’m using PyTorch built from source

**Comment by zxybazh** [comment]
Yes I can see the same warning `CUDA driver initialization failed, you might not have a CUDA gpu.` I can also get `torch.cuda.is_available()` returning `True` for me. When using your script, I don't see the same Cuda free error. My pytorch with cuda support is installed via pip so that could probably be the difference here.

**Comment by KangHe000** [comment]
Thanks, I will update my cuda driver, or run the test without importing PT.

**Comment by zxybazh** [comment]
I noticed that after reinstall my PyTorch to be cpu-only version, this issue is not reproducible any more. You can try this as well.
